### PR TITLE
Time  input integrated, general touch ups

### PR DESCRIPTION
**Pull request by mihaildicoski**
Time input fully integrated (yet to be tested). View appliances, generators integrated. General UI touchups on dashboard including more error handlng, no more up/down arrows on input of type number. Reset to market price button does not show annoying default prompt to input valid integer anymore. First node is automatically selected on analytics page. Analytics route added on desktop navbar (both). Error messages for invalid time input also included - with the option to stick to default time periods.

### CODE REVIEW

**Review by Danieldv-s — CHANGES_REQUESTED** [review]
I think you forgot to merge dev into your branch first - the yml files seem reverted

**Comment by mihaildicoski** [comment]
merged dev earlier today,  just tried again now. Says already up to date. Any suggestions?

**Comment by Danieldv-s** [comment]
For some reason it's still changing the workflow and backend files, maybe just copy and paste these from dev? Everything on frontend seems fine

**Comment by Danieldv-s** [comment]
I'll go ahead and do it quickly
@mihaildicoski Just remember to pull again later

**Review by Danieldv-s — APPROVED** [review]

**Pull request merged**
